run:
  go: '1.21'
  modules-download-mode: 'readonly'
  allow-serial-runners: true
  print-resources-usage: true
output:
  formats: 'colored-line-number'
linters:
  disable-all: true
  enable:
    - 'errcheck'
    - 'goimports'
    - 'govet'
    - 'staticcheck'
linters-settings:
  errcheck:
    exclude-functions:
      - (*bytes.Buffer).WriteByte
      - (*strings.Builder).WriteByte
      - (*strings.Builder).WriteString
    check-type-assertions: true
    disable-default-exclusions: true
  goimports:
    local-prefixes: 'toolkit'
  govet:
    shadow: true
    enable-all: true
    disable:
      - 'fieldalignment'
  staticcheck:
    checks: ["all"]
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
