#!/usr/bin/env bash
set -e

basename="${0##*/}"
triplet="${basename##cgotool-wrapper\.}"

if [[ "${triplet}" =~ ^x86_64.*$ ]]; then
  export GOARCH=amd64; export GOAMD64=v3
elif [[ "${triplet}" =~ ^aarch64.*$ ]]; then
  export GOARCH=arm64
elif [[ "${triplet}" =~ ^i686.*$ ]]; then
  export GOARCH=386
elif [[ "${triplet}" =~ ^armv7.*$ ]]; then
  export GOARCH=arm
fi

export CGO_ENABLED=1
export GOTOOLCHAIN=local
export GOOS=windows
export AR="${CROSS_TOOLCHAIN_ROOT}/bin/${triplet}-ar"
export CC="${CROSS_TOOLCHAIN_ROOT}/bin/${triplet}-clang"
export CXX="${CROSS_TOOLCHAIN_ROOT}/bin/${triplet}-clang++"
export PKG_CONFIG="${CROSS_TOOLCHAIN_PKGCONF}"

exec go "$@"
